import { sha256Canonical } from "../evidence/canonical.js";
import { MAX_BODY, MAX_COMMENT, MAX_STRING, MAX_TITLE } from "./limits.js";
import type {
  DuplicateAssessment,
  DuplicateRecommendation,
  DuplicateSearch,
  DuplicateState,
  EvidenceDelta,
  UpstreamPreviewRequest,
  UpstreamRoute,
} from "./types.js";
import { assertNoLeakPaths, redactText } from "../core/redact.js";

function materialDelta(delta: EvidenceDelta): boolean {
  return delta.items.some((i) => i.material === true);
}

function evidenceDeltaHash(delta: EvidenceDelta): string | null {
  if (delta.items.length === 0) return null;
  return sha256Canonical(delta.items);
}

/** Exact duplicate requires both exact similarity AND mechanism_match. */
function pickBestExact(search: DuplicateSearch) {
  return (
    search.candidates.find(
      (c) => c.similarity === "exact" && c.mechanism_match === true,
    ) ?? null
  );
}

/** Related includes related similarity OR exact symptom without mechanism match. */
function pickRelated(search: DuplicateSearch) {
  return search.candidates.filter(
    (c) =>
      c.similarity === "related" ||
      (c.similarity === "exact" && c.mechanism_match === false),
  );
}

function sanitizeLine(s: string, max = MAX_TITLE): string {
  return assertNoLeakPaths(redactText(s)).slice(0, max);
}

/** Exact technical strings: preserve up to MAX_STRING after mandatory redaction. */
function sanitizeTechnical(s: string): string {
  return sanitizeLine(s, MAX_STRING);
}

function buildNewIssueBody(req: UpstreamPreviewRequest): string {
  const lines: string[] = [
    "## Observed facts",
    ...req.observed_facts.map((f) => `- ${sanitizeLine(f)}`),
    "",
    "## Actual behavior",
    sanitizeLine(req.actual_behavior),
    "",
    "## Technical signals",
    ...req.technical_signals.map((t) => `- ${sanitizeLine(t)}`),
    "",
    "## Platform / version",
    `- platform: ${req.platform.os ?? "unknown"}${req.platform.unknown_reason ? ` (${sanitizeLine(req.platform.unknown_reason)})` : ""}`,
    `- arch: ${req.platform.arch ?? "unknown"}`,
    `- codex_version: ${req.codex_version ?? req.version_unknown_reason ?? "unknown"}`,
    `- surface: ${req.surface}`,
    "",
    "## Reproduction",
    `- quality: ${req.reproduction.quality}`,
  ];
  if (req.reproduction.intermittent_marker) {
    lines.push(
      `- intermittent: ${sanitizeLine(req.reproduction.intermittent_marker)}`,
    );
  }
  if (req.reproduction.steps.length > 0) {
    lines.push("", "### Steps");
    for (const step of req.reproduction.steps) {
      lines.push(`1. ${sanitizeLine(step)}`);
    }
  }
  if (req.error_strings.length > 0) {
    lines.push("", "## Exact errors");
    for (const e of req.error_strings) {
      lines.push("```", sanitizeTechnical(e), "```");
    }
  }
  if (req.command_strings.length > 0) {
    lines.push("", "## Exact commands");
    for (const c of req.command_strings) {
      lines.push("```", sanitizeTechnical(c), "```");
    }
  }
  if (req.user_reports.length > 0) {
    lines.push("", "## User reports (not verified facts)");
    for (const u of req.user_reports) {
      lines.push(`- ${sanitizeLine(u)}`);
    }
  }
  if (req.hypotheses.length > 0) {
    lines.push("", "## Hypotheses (not proven)");
    for (const h of req.hypotheses) {
      lines.push(`- ${sanitizeLine(h)}`);
    }
  }
  lines.push(
    "",
    "---",
    "_Draft generated by Codex ChangeGuard (preview only; no external write)._",
  );
  return lines.join("\n").slice(0, MAX_BODY);
}

function buildDeltaComment(
  req: UpstreamPreviewRequest,
  issueId: string,
): string {
  const material = req.evidence_delta.items.filter((i) => i.material);
  const lines: string[] = [
    `## Evidence Delta for ${sanitizeLine(issueId)}`,
    "",
    "Material new evidence not present on the existing Issue:",
    "",
  ];
  for (const item of material) {
    lines.push(`- **${item.kind}**: ${sanitizeLine(item.summary)}`);
  }
  lines.push(
    "",
    "### Local context",
    `- platform: ${req.platform.os ?? "unknown"} / ${req.platform.arch ?? "unknown"}`,
    `- version: ${req.codex_version ?? req.version_unknown_reason ?? "unknown"}`,
    `- surface: ${req.surface}`,
  );
  if (req.error_strings[0]) {
    lines.push(
      `- error: \`${sanitizeTechnical(req.error_strings[0]).slice(0, MAX_STRING)}\``,
    );
  }
  lines.push(
    "",
    "_Structured comment preview only — Ticket 11 requires separate confirmation before any write._",
  );
  return lines.join("\n").slice(0, MAX_COMMENT);
}

function draftTitle(req: UpstreamPreviewRequest): string {
  const base =
    req.error_strings[0] ||
    req.actual_behavior ||
    req.observed_facts[0] ||
    "Codex product bug";
  return sanitizeLine(base).slice(0, 120);
}

/**
 * Duplicate classification with exact enums and zero-delta reaction-only rule.
 */
export function assessDuplicate(
  req: UpstreamPreviewRequest,
  route: UpstreamRoute,
): DuplicateAssessment & { draft_title: string | null } {
  if (route === "BUGCROWD") {
    return {
      state: "NEW_INCIDENT",
      matched_issue_id: null,
      matched_issue_url: null,
      evidence_delta_material: materialDelta(req.evidence_delta),
      evidence_delta_hash: evidenceDeltaHash(req.evidence_delta),
      recommendation: "private_report",
      draft_body: null,
      draft_comment: null,
      cross_link_issue_ids: [],
      draft_title: null,
    };
  }
  if (route === "OPENAI_SUPPORT") {
    return {
      state: "NEW_INCIDENT",
      matched_issue_id: null,
      matched_issue_url: null,
      evidence_delta_material: false,
      evidence_delta_hash: null,
      recommendation: "contact_support",
      draft_body: null,
      draft_comment: null,
      cross_link_issue_ids: [],
      draft_title: null,
    };
  }
  if (route === "GITHUB_DISCUSSIONS") {
    return {
      state: "NEW_INCIDENT",
      matched_issue_id: null,
      matched_issue_url: null,
      evidence_delta_material: materialDelta(req.evidence_delta),
      evidence_delta_hash: evidenceDeltaHash(req.evidence_delta),
      recommendation: "open_discussion",
      draft_body: buildNewIssueBody(req),
      draft_comment: null,
      cross_link_issue_ids: [],
      draft_title: draftTitle(req),
    };
  }

  // GITHUB_ISSUE path
  if (!req.duplicate_search.searched) {
    // Without search, treat as blocked new-incident candidate — still draft for preview
    // but gate will fail the search requirement.
    return {
      state: "NEW_INCIDENT",
      matched_issue_id: null,
      matched_issue_url: null,
      evidence_delta_material: materialDelta(req.evidence_delta),
      evidence_delta_hash: evidenceDeltaHash(req.evidence_delta),
      recommendation: "open_new",
      draft_body: buildNewIssueBody(req),
      draft_comment: null,
      cross_link_issue_ids: [],
      draft_title: draftTitle(req),
    };
  }

  const exact = pickBestExact(req.duplicate_search);
  const related = pickRelated(req.duplicate_search);
  const hasMaterial = materialDelta(req.evidence_delta);

  if (exact) {
    const state: DuplicateState = "EXACT_DUPLICATE";
    if (!hasMaterial) {
      // Zero Evidence Delta: recommend subscribe/upvote only — no body/comment
      // and no cross-link actions (reaction-only compliance).
      return {
        state,
        matched_issue_id: exact.issue_id,
        matched_issue_url: exact.url,
        evidence_delta_material: false,
        evidence_delta_hash: evidenceDeltaHash(req.evidence_delta),
        recommendation: "subscribe_or_upvote" satisfies DuplicateRecommendation,
        draft_body: null,
        draft_comment: null,
        cross_link_issue_ids: [],
        draft_title: null,
      };
    }
    // Material Evidence Delta → structured comment preview only.
    return {
      state,
      matched_issue_id: exact.issue_id,
      matched_issue_url: exact.url,
      evidence_delta_material: true,
      evidence_delta_hash: evidenceDeltaHash(req.evidence_delta),
      recommendation: "comment_with_delta",
      draft_body: null,
      draft_comment: buildDeltaComment(req, exact.issue_id),
      cross_link_issue_ids: related.map((r) => r.issue_id),
      draft_title: null,
    };
  }

  if (related.length > 0) {
    // Related but distinct mechanisms remain separate and cross-linked.
    return {
      state: "RELATED_NOT_SAME",
      matched_issue_id: related[0]!.issue_id,
      matched_issue_url: related[0]!.url,
      evidence_delta_material: hasMaterial,
      evidence_delta_hash: evidenceDeltaHash(req.evidence_delta),
      recommendation: "cross_link_related",
      draft_body: buildNewIssueBody(req),
      draft_comment: null,
      cross_link_issue_ids: related.map((r) => r.issue_id),
      draft_title: draftTitle(req),
    };
  }

  return {
    state: "NEW_INCIDENT",
    matched_issue_id: null,
    matched_issue_url: null,
    evidence_delta_material: hasMaterial,
    evidence_delta_hash: evidenceDeltaHash(req.evidence_delta),
    recommendation: "open_new",
    draft_body: buildNewIssueBody(req),
    draft_comment: null,
    cross_link_issue_ids: [],
    draft_title: draftTitle(req),
  };
}
