export {
  buildMacosCapabilities,
  enumerateMacosCandidates,
  readMacosCodexVersionProvenance,
  readCoarseOsVersion,
  assertDisposableTarget,
  assertHarnessOutputDir,
  captureActiveCodexHomeWitness,
  isolationDigestOf,
  listTrustedDisposableRoots,
  macosRegisteredAliases,
  isMacosOperationRegistered,
  PROTECTED_ROOTS,
  type MacosAdapterCaps,
  type DisposableTargetOptions,
} from "./adapter.js";
